"""Second Initial

Revision ID: 890eb7917370
Revises: 95a6940bf6e7
Create Date: 2023-09-03 12:36:03.130796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '890eb7917370'
down_revision: Union[str, None] = '95a6940bf6e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('clients_company_id_fkey', 'clients', type_='foreignkey')
    op.create_foreign_key(None, 'clients', 'companies', ['company_id'], ['id'], ondelete='SET NULL')
    op.alter_column('feedbacks', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('projects', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('projects', 'feedback_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('services', 'calculation_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('services', 'calculation_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('projects', 'feedback_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('projects', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('feedbacks', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.create_foreign_key('clients_company_id_fkey', 'clients', 'companies', ['company_id'], ['id'])
    op.alter_column('clients', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
