"""Second Initial

Revision ID: 95a6940bf6e7
Revises: 
Create Date: 2023-09-03 12:24:57.401357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95a6940bf6e7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('feedbacks_client_id_fkey', 'feedbacks', type_='foreignkey')
    op.create_foreign_key(None, 'feedbacks', 'clients', ['client_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('projects_category_id_fkey', 'projects', type_='foreignkey')
    op.drop_constraint('projects_feedback_id_fkey', 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'feedbacks', ['feedback_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'projects', 'directions', ['category_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('projects_image_parent_id_fkey', 'projects_image', type_='foreignkey')
    op.create_foreign_key(None, 'projects_image', 'projects', ['parent_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('services_calculation_id_fkey', 'services', type_='foreignkey')
    op.create_foreign_key(None, 'services', 'calculations', ['calculation_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.create_foreign_key('services_calculation_id_fkey', 'services', 'calculations', ['calculation_id'], ['id'])
    op.drop_constraint(None, 'projects_image', type_='foreignkey')
    op.create_foreign_key('projects_image_parent_id_fkey', 'projects_image', 'projects', ['parent_id'], ['id'])
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key('projects_feedback_id_fkey', 'projects', 'feedbacks', ['feedback_id'], ['id'])
    op.create_foreign_key('projects_category_id_fkey', 'projects', 'directions', ['category_id'], ['id'])
    op.drop_constraint(None, 'feedbacks', type_='foreignkey')
    op.create_foreign_key('feedbacks_client_id_fkey', 'feedbacks', 'clients', ['client_id'], ['id'])
    # ### end Alembic commands ###
