"""Second

Revision ID: e0a0d6f3320b
Revises: 890eb7917370
Create Date: 2023-09-06 19:38:47.575905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0a0d6f3320b'
down_revision: Union[str, None] = '890eb7917370'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('considerations', sa.Column('file', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('considerations', 'file')
    # ### end Alembic commands ###
